---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 徐飞扬.
--- DateTime: 2022/11/9 14:12
---
--比较线程标示二号锁中标示是否一致
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    --释放锁
    return redis.call('del',KEYS[1])
end